# Generated by Django 5.1.4 on 2024-12-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_address_lat_remove_address_lng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extras',
        ),
    ]
